sudo: false
language: python
env:
  matrix:
  - HTTPie=0.7.2
  - HTTPie=0.8.0
  - HTTPie=0.9.4
  - HTTPie=0.9.6
  global:
  - MOST_TESTED_PYTHON_VERSION=2.7
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt --upgrade
- pip uninstall -y httpie
- pip install httpie==$HTTPie
script:
- make test-clean
- make test-unit
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == $MOST_TESTED_PYTHON_VERSION && $HTTPie == 0.9.3 ]]; then pip install
  --quiet python-coveralls && make report-coverage && coveralls; fi
- make check-style
notifications:
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      secure: jXjeY5Rh4nflRST0oAzwJbOTm23ddcViq2rXhQbbVD5Dz/G177tczBuwPSvrGmZlaipSillBWHMii+De/cPvDBCfYhLZRLk/pJJCbm9HXwzbX19vJtnmMzi0jCEYJk9ayaDr4s56Qn7GCMM89TRYhpEY8JpIPyaYhbsh38CL6czv9K0XcfrWGHQHoIdVvOVtrgeoYWPqmDWwKKKBVjS7X5uVZzEnk5Pg/+pC0lDGI1HDyE7tTJpI1ApHu3v/6iMuR9aDFepQXh7XjzhdopFSpSY0MPT1/6BrWH0pU8MqXjTwbL32XFDBswKYkDcCgP0OIU1AtYMNAVcSTS1kth4NF6BiqrNSWyM68Dmx3Gz09qEk3gylsOoxvoIKOUvJ+s6jo1q93tW+d3Vb9AlGE4Gi78W0uhoLOBbwaVnMUY5b+LW1HdTkDNpORJ3iTn1/CRPVA711fGv4e8P7EEBdcWWCufdU1cHMiQKTdY8NfiM2BXQVi+Y62h+61CxOMbVuY1esjRkIbEh2d+9Xrs5f1YMpBI+pH7VJlkYduPJqDvm6sU+JoAJEUc/WtU3BvIQtY0n+5jvWs9Rnbx7W5JPFMGrnxVMlhVWkiiUKDpARhSpHHuQ9zQuMcRMIrXk7/9ZiRbwsrQYOCw+pwz75RJCw8yT6LgsHWqBz7mZ6D2n2DVQtJl4=
